// GENERATED by scripts/freeze-explore-layout.mjs — do not edit by hand.
// The frozen shipped EXPLORE field (Session 12). graph.ts reads the shipped
// prefix from here so appended nodes can relax against it without moving it.
// Re-run the generator ONLY to intentionally re-seed the constellation; the
// snapshot test fails if these drift from makeGraph()'s shipped prefix.

export interface FrozenNode {
  id: string
  x: number
  y: number
  z: number
  deg: number
}

export interface FrozenEdge {
  a: number
  b: number
  w: number
  implied: boolean
}

// The shipped ids in layout order. graph.ts checks the registry's first
// FROZEN_NODES.length ids against this as a PREFIX (appends extend past it).
export const FROZEN_ID_ORDER = 'sensi|neurospace|huddle|lungs|legoarch|ballooning|podcast|soma|mars|cappelletti|xr|bim|neuroaes|solvers|genai|xreal|comfort|drawiface|evosearch|heritage|respond'

export const FROZEN_NODES: FrozenNode[] = [
  { id: 'sensi', x: 91.0055622390593, y: 44.281124988699275, z: 44.79057204329405, deg: 6 },
  { id: 'neurospace', x: -7.036619667984659, y: 7.8056698422910555, z: 63.525507790523456, deg: 10 },
  { id: 'huddle', x: -85.96594870741262, y: 43.487620321292816, z: 56.63519672185971, deg: 5 },
  { id: 'lungs', x: -71.73114829258343, y: 36.45739573675811, z: 147.44722248442423, deg: 3 },
  { id: 'legoarch', x: -112.34024372315629, y: 1.7439965738000174, z: -89.62952562073372, deg: 3 },
  { id: 'ballooning', x: -68.74259762840816, y: -47.497621957284565, z: -3.9796630281966063, deg: 7 },
  { id: 'podcast', x: 57.15349364397085, y: 3.2569314661549256, z: -69.35749212988983, deg: 7 },
  { id: 'soma', x: -15.139520084217764, y: -144.1856717769221, z: -45.98542067475708, deg: 2 },
  { id: 'mars', x: -2.2595499177105163, y: -77.55787966276912, z: -136.05659874783913, deg: 2 },
  { id: 'cappelletti', x: -67.15439981740364, y: 44.82617303444095, z: -26.198009199239372, deg: 6 },
  { id: 'xr', x: -2.611474759421383, y: 100.69785903521142, z: -121.34954008305606, deg: 2 },
  { id: 'bim', x: 100.5183669265913, y: 11.467138949718636, z: -5.265573140097496, deg: 6 },
  { id: 'neuroaes', x: 104.9359855079001, y: 88.36190711701431, z: -30.155374931991034, deg: 3 },
  { id: 'solvers', x: -120.84842433938701, y: -1.1003303175152577, z: 26.30964424998895, deg: 4 },
  { id: 'genai', x: -35.96249084319687, y: -10.416971878036373, z: -141.94226256925788, deg: 3 },
  { id: 'xreal', x: 79.96111922659485, y: 58.43222529110509, z: -158.598640152214, deg: 2 },
  { id: 'comfort', x: 111.48966234833362, y: -16.148590936501467, z: 75.06234272705548, deg: 4 },
  { id: 'drawiface', x: 3.859908635764779, y: 76.27616402548925, z: 170.46016442761837, deg: 2 },
  { id: 'evosearch', x: 55.90862485383977, y: -29.469453742135972, z: 145.24896445247745, deg: 2 },
  { id: 'heritage', x: -41.58007764680765, y: -165.4712278962904, z: 18.203461154550524, deg: 2 },
  { id: 'respond', x: 68.58128047570646, y: -37.345909174360045, z: 21.894170360951232, deg: 5 },
]

export const FROZEN_EDGES: FrozenEdge[] = [
  { a: 0, b: 6, w: 3, implied: false },
  { a: 0, b: 11, w: 2, implied: false },
  { a: 0, b: 12, w: 2, implied: false },
  { a: 0, b: 16, w: 2, implied: false },
  { a: 0, b: 20, w: 2, implied: false },
  { a: 1, b: 2, w: 2, implied: false },
  { a: 1, b: 3, w: 2, implied: false },
  { a: 1, b: 5, w: 2, implied: false },
  { a: 1, b: 9, w: 2, implied: false },
  { a: 1, b: 11, w: 2, implied: false },
  { a: 1, b: 13, w: 2, implied: false },
  { a: 1, b: 16, w: 2, implied: false },
  { a: 1, b: 20, w: 2, implied: false },
  { a: 2, b: 5, w: 2, implied: false },
  { a: 2, b: 9, w: 2, implied: false },
  { a: 2, b: 13, w: 2, implied: false },
  { a: 4, b: 5, w: 2, implied: false },
  { a: 4, b: 9, w: 2, implied: false },
  { a: 4, b: 14, w: 2, implied: false },
  { a: 5, b: 7, w: 2, implied: false },
  { a: 5, b: 9, w: 3, implied: false },
  { a: 5, b: 13, w: 2, implied: false },
  { a: 6, b: 8, w: 2, implied: false },
  { a: 6, b: 11, w: 3, implied: false },
  { a: 6, b: 12, w: 2, implied: false },
  { a: 6, b: 14, w: 2, implied: false },
  { a: 6, b: 20, w: 2, implied: false },
  { a: 7, b: 19, w: 2, implied: false },
  { a: 8, b: 14, w: 2, implied: false },
  { a: 9, b: 10, w: 2, implied: false },
  { a: 9, b: 13, w: 2, implied: false },
  { a: 10, b: 15, w: 2, implied: false },
  { a: 11, b: 12, w: 2, implied: false },
  { a: 11, b: 16, w: 2, implied: false },
  { a: 11, b: 20, w: 3, implied: false },
  { a: 16, b: 20, w: 3, implied: false },
  { a: 3, b: 2, w: 1, implied: true },
  { a: 15, b: 6, w: 1, implied: true },
  { a: 17, b: 1, w: 1, implied: true },
  { a: 17, b: 3, w: 1, implied: true },
  { a: 18, b: 0, w: 1, implied: true },
  { a: 18, b: 1, w: 1, implied: true },
  { a: 19, b: 5, w: 1, implied: true },
]
